### ISSUE TITLE
Pickling of functions in a file loaded in a Sage Worksheet fails

### ISSUE THREAD

**Issue by nvcleemp** [sagemath/cloud#198]
Below is a small example demonstrating the issue:

* First create a file called `test.py` with the following content:
```python
def test_function(): pass
```
* Next open a Sage Worksheet and execute the following code:
```python
load('test.py')
save(test_function, 'test.sobj')
```
* This crashes with the following traceback:
```
Error in lines 1-1
Traceback (most recent call last):
  File "/projects/8d39729d-4566-4056-84e2-c636147c3fc3/.sagemathcloud/sage_server.py", line 879, in execute
    exec compile(block+'\n', '', 'single') in namespace, locals
  File "", line 1, in <module>
  File "sage/structure/sage_object.pyx", line 989, in sage.structure.sage_object.save (build/cythonized/sage/structure/sage_object.c:11348)
    s = cPickle.dumps(obj, protocol=2)
TypeError: expected string or Unicode object, NoneType found
```
* Switching to `pickle` instead of `cPickle` makes it more obvious what the issue is:
```python
import pickle
pickle.dumps(test_function, protocol=2)
```
which crashes with the following traceback:
```
Error in lines 2-2
Traceback (most recent call last):
  File "/projects/8d39729d-4566-4056-84e2-c636147c3fc3/.sagemathcloud/sage_server.py", line 879, in execute
    exec compile(block+'\n', '', 'single') in namespace, locals
  File "", line 1, in <module>
  File "/projects/sage/sage-6.7/local/lib/python/pickle.py", line 1374, in dumps
    Pickler(file, protocol).dump(obj)
  File "/projects/sage/sage-6.7/local/lib/python/pickle.py", line 224, in dump
    self.save(obj)
  File "/projects/sage/sage-6.7/local/lib/python/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/projects/sage/sage-6.7/local/lib/python/pickle.py", line 748, in save_global
    (obj, module, name))
PicklingError: Can't pickle <function test_function at 0x7f1af4bdccf8>: it's not found as __main__.test_function
```

If you try the same thing in command-line Sage, then everything works as you would expect.

**Comment by nvcleemp** [comment]
This is now sagemathinc/smc#2
