### ISSUE TITLE
The search_doc command is sometimes not working

### ISSUE THREAD

**Issue by GregoryBard** [sagemath/cloud#205]
The command search_doc, such as

search_doc("lagrange multipliers")

does not work on my SageMathCloud project, "Gregory Collaborations on Sage."

https://cloud.sagemath.com/projects/c096352d-b392-499a-8899-6bfa794d7504/files/smc.wiki/temporary%20scratch%20for%20commands.sagews

Instead, I get this error message:

Error in lines 1-1
Traceback (most recent call last):
  File "/projects/sage/sage-6.10/local/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 948, in execute
    exec compile(block+'\n', '', 'single') in namespace, locals
  File "", line 1, in <module>
  File "/projects/sage/sage-6.10/local/lib/python2.7/site-packages/sage/misc/sagedoc.py", line 1139, in search_doc
    **kwds)
  File "/projects/sage/sage-6.10/local/lib/python2.7/site-packages/sage/misc/sagedoc.py", line 925, in _search_src_or_doc
    pager.pager()(results)
  File "/projects/sage/sage-6.10/local/lib/python2.7/site-packages/IPython/core/page.py", line 274, in page
    return pager_page(data, start, screen_lines, pager_cmd)
  File "/projects/sage/sage-6.10/local/lib/python2.7/site-packages/IPython/core/page.py", line 234, in pager_page
    pager_encoding = pager.encoding or sys.stdout.encoding
AttributeError: 'BufferedOutputStream' object has no attribute 'encoding'

**Comment by GregoryBard** [comment]
Around 2 pm, Wisconsin time, @hsy noted:

the odd thing is, that it works on those nodes which are restarted, i.e. those free ones. since there are no significant differences, I assume that rebooting the member machines should also solve this. but sure, make an issue, reminds us to check on this.
